// API Key action types
export const SET_API_KEY = 'SET_API_KEY';

// Repository action types 
export const REQUEST_REPOS_PENDING = 'REQUEST_REPOS_PENDING';
export const REQUEST_REPOS_SUCCESS = 'REQUEST_REPOS_SUCCESS';
export const REQUEST_REPOS_FAILURE = 'REQUEST_REPOS_FAILURE';
export const SET_SELECTED_REPO = 'SET_SELECTED_REPO';

// Issues action types
export const REQUEST_ISSUES_PENDING = 'REQUEST_ISSUES_PENDING';
export const REQUEST_ISSUES_SUCCESS = 'REQUEST_ISSUES_SUCCESS';
export const REQUEST_ISSUES_FAILURE = 'REQUEST_ISSUES_FAILURE';
export const UPDATE_ISSUES_ORDER = 'UPDATE_ISSUES_ORDER';
